# Site settings
title: Masha Medvedeva
email: m.medvedeva@rug.nl
#url: https://example.github.io
description: ""
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: masha-medvedeva

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/JudgyLinguist
#  - title: linkedin
#    url: https://www.linkedin.com/in/masha-medvedeva/


# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-minimal